import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar/Navbar'
import InitializeTheme from './components/Navbar/InitializeTheme'
import Providers from './provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
   
  return (
    <html lang="en" data-theme="fantasy">
      <Providers>
        
      <InitializeTheme/>
      <body className={inter.className}>
      <Navbar/>
      <main>{children}</main> 
      </body>
      
      </Providers>
    </html>
  )
}
