import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar/Navbar'
import Providers from './provider'
import { Playfair_Display, Open_Sans } from 'next/font/google'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ['latin'] })

const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ["300", "400", "500", "700"]
})

const playFair = Playfair_Display({
  subsets: ['latin'],
  weight: ["400", "700"]
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
   
  return (
    <html lang="en" data-theme="cupcake">
          
      <body>
      <Providers>
      <Navbar/>
      <main>{children}</main> 
      <ToastContainer />
      </Providers>
      </body>
      
    </html>
  )
}
